# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_body_category_color_fuel_gear_painting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='item_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='brands',
            name='item_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='category',
            name='item_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='color',
            name='item_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='item_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='item_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='gear',
            name='item_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='painting',
            name='item_id',
            field=models.CharField(max_length=120),
        ),
    ]
